### ISSUE TITLE
NPE at opening Application.properties file

### ISSUE THREAD

**Issue by makiam** [AlexFalappa/nb-springboot#116]
Steps to reproduce:
I have Non-Springboot maven project and I have an  Application.properties file under it. Once I try to open It I see an exception:
```
java.lang.NullPointerException
	at com.github.alexfalappa.nbspringboot.projects.service.spi.SpringBootServiceImpl.getPropertyMetadata(SpringBootServiceImpl.java:155)
	at com.github.alexfalappa.nbspringboot.cfgprops.highlighting.UnknownPropsHighlightingTask.internalRun(UnknownPropsHighlightingTask.java:81)
	at com.github.alexfalappa.nbspringboot.cfgprops.highlighting.BaseHighlightingTask.run(BaseHighlightingTask.java:56)
	at com.github.alexfalappa.nbspringboot.cfgprops.highlighting.BaseHighlightingTask.run(BaseHighlightingTask.java:41)
```

**Comment by AlexFalappa** [comment]
I could not reproduce your issue by creating a new maven application project (non spring boot).

How did you get that exception? Have you created a spring boot project and then afterwards removed all the spring boot dependencies?

**Comment by makiam** [comment]
My maven project is not related to Spring at all, https://github.com/makiam/SAFF  Once I installed Your plugin I see that some Application*.properties files displayed with Spring boot icon. When I clicked it to open I see this exception.

**Comment by AlexFalappa** [comment]
Thanks for the additional info. Will have a look.
