### ISSUE TITLE
NPE while opening configuration properties editor

### ISSUE THREAD

**Issue by AlexFalappa** [AlexFalappa/nb-springboot#122]
Got this NPE while opening an  `application.properties` file after having modified a `@ConfigurationProperties` class and never having triggered a completion before (the `SpringBootService` was probably not initialized yet):

```
java.lang.NullPointerException
	at com.github.alexfalappa.nbspringboot.projects.service.spi.SpringBootServiceImpl.getPropertyMetadata(SpringBootServiceImpl.java:161)
	at com.github.alexfalappa.nbspringboot.cfgprops.highlighting.UnknownPropsHighlightingTask.internalRun(UnknownPropsHighlightingTask.java:81)
	at com.github.alexfalappa.nbspringboot.cfgprops.highlighting.BaseHighlightingTask.run(BaseHighlightingTask.java:56)
	at com.github.alexfalappa.nbspringboot.cfgprops.highlighting.BaseHighlightingTask.run(BaseHighlightingTask.java:41)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callParserResultTask(TaskProcessor.java:584)
[catch] at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:809)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:304)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:725)
	at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:686)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
```

**Comment by AlexFalappa** [comment]
Probably a duplicate of #116
