### ISSUE TITLE
Exception is thrown when saving changes in pom.xml

### ISSUE THREAD

**Issue by wernerblanck** [AlexFalappa/nb-springboot#139]
Hi, after saving a modification in the pom.xml a warning message and an exception is thrown:

![image](https://user-images.githubusercontent.com/36088214/40374238-104485d8-5dbf-11e8-9fca-1ba1318e7579.png)
the message continues with the project's directory path.

The exception is 
`java.lang.NullPointerException
	at com.github.alexfalappa.nbspringboot.projects.service.impl.SpringBootServiceImpl.adjustNbActions(SpringBootServiceImpl.java:374)
	at com.github.alexfalappa.nbspringboot.projects.service.impl.SpringBootServiceImpl.refresh(SpringBootServiceImpl.java:122)
	at com.github.alexfalappa.nbspringboot.projects.service.impl.SpringBootServiceImpl$1.propertyChange(SpringBootServiceImpl.java:271)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at org.netbeans.modules.maven.api.NbMavenProject.doFireReload(NbMavenProject.java:573)
	at org.netbeans.modules.maven.api.NbMavenProject.access$200(NbMavenProject.java:95)
	at org.netbeans.modules.maven.api.NbMavenProject$AccessorImpl.doFireReload(NbMavenProject.java:141)
	at org.netbeans.modules.maven.NbMavenProjectImpl$1.run(NbMavenProjectImpl.java:151)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)`

**Comment by wernerblanck** [comment]
Besides the message, an empty nbactions.tmp file is created at the root of the project.

**Comment by AlexFalappa** [comment]
Hi @wernerblanck , are you using the last version of the plugin?

I remember tweaking some things on `nbactions.xml` file management recently.

**Comment by everflux** [comment]
I have the same issue, using version 2.0 from March. Problem occurs with NB 8 and NB 9.0.0 RC1 (incubating).

**Comment by wernerblanck** [comment]
Yes, it's Version 2.0 (Mar 2018): Reactive Goodies, from NB Plugin Portal.
Let me know if you need more information.
Regards

**Comment by mtbadi39** [comment]
I have the same issue also  :
![image](https://user-images.githubusercontent.com/8750684/41664749-57a46be6-749e-11e8-9780-672b4d71c0fd.png)

```
java.lang.NullPointerException
	at com.github.alexfalappa.nbspringboot.projects.service.impl.SpringBootServiceImpl.adjustNbActions(SpringBootServiceImpl.java:374)
	at com.github.alexfalappa.nbspringboot.projects.service.impl.SpringBootServiceImpl.refresh(SpringBootServiceImpl.java:122)
	at com.github.alexfalappa.nbspringboot.projects.service.impl.SpringBootServiceImpl$1.propertyChange(SpringBootServiceImpl.java:271)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at org.netbeans.modules.maven.api.NbMavenProject.doFireReload(NbMavenProject.java:573)
	at org.netbeans.modules.maven.api.NbMavenProject.access$200(NbMavenProject.java:95)
	at org.netbeans.modules.maven.api.NbMavenProject$AccessorImpl.doFireReload(NbMavenProject.java:141)
	at org.netbeans.modules.maven.NbMavenProjectImpl$1.run(NbMavenProjectImpl.java:151)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

```
Config :
```
NetBeans IDE 8.2 (Build 201609300101) updated to version NetBeans 8.2 Patch 2
Java: 1.8.0_171; HotSpot(TM) 64-Bit Server VM 25.171-b11
Windows 7 version 6.1 running on amd64; Cp1252; fr_FR (nb)
Plugin Version : 2.0 (Mar 2018)
Spring Boot 2.0.3.RELEASE
```
Action to reproduce : mvn clean (no project is running in the ide !)

**Comment by dellasavia** [comment]
I had the same error. If I delete manually the file nbactions.tmp, it does work normally until the next build process.

**Comment by sgraff** [comment]
I run into the same problem, finally I uninstall it and install a older version.  Please fix this problem, it is really sucks.

**Comment by everflux** [comment]
Thanks!

**Comment by dellasavia** [comment]
So, what I would do to resolve this issue? Install an older version?

**Comment by AlexFalappa** [comment]
@dellasavia, the bug _should_ be fixed in master, will be in next version (2.0.1) that I am going to release soon

**Comment by AlexFalappa** [comment]
To all interested, I couldn't manage to reproduce this bug, I have however reorganized the logic to guard against possible NullPointerEception at the code reported in the stack traces.

**Comment by dellasavia** [comment]
I just installed the update and works fine to me! Tks so much, @AlexFalappa

**Comment by mtbadi39** [comment]
Ok, i can confirme that was fixed.
Apache NetBeans 9.0 + Oracle JDK 10 + Windows 7 64bits
Tks so much, :+1:  @AlexFalappa

**Comment by AlexFalappa** [comment]
Thank you @mtbadi39 !

**Comment by eggmatters** [comment]
Can this issue be re-evaluated? I get this popup everytime any mvn task executes:

```Product Version: Apache NetBeans IDE 9.0 (Build incubator-netbeans-release-334-on-20180708)
Updates: NetBeans IDE is updated to version NetBeans 8.2 Patch 2
Java: 11.0.1; OpenJDK 64-Bit Server VM 11.0.1+13
Runtime: OpenJDK Runtime Environment 11.0.1+13
System: Mac OS X version 10.14.3 running on x86_64; UTF-8; en_US (nb)```

**Comment by AlexFalappa** [comment]
@eggmatters I would prefer you open up a new issue but **please**:
* try to describe how you got the error in the first place, i.e. describe as precisely as possible what you did before stumbling upon this beaviour
* attach your NetBeans log (it is in `<netbeans_user_dir>/var/log/message.log`, the user dir is indicated in the about dialog)
* remove any nbactions.tmp leftover file before opening the project in NetBeans to see if it gets you out of the error loop
