### ISSUE TITLE
Search Spring Boot dependencies is broken

### ISSUE THREAD

**Issue by AlexFalappa** [AlexFalappa/nb-springboot#149]
Typing in the search field in _Spring Initializr_ project wizard or _Add Spring Boot Dependencies_ dialog causes a `NullPointerException`:
```
SEVERE [global]
java.lang.NullPointerException
	at com.github.alexfalappa.nbspringboot.projects.initializr.BootDependenciesPanel.cbFilter(BootDependenciesPanel.java:358)
	at com.github.alexfalappa.nbspringboot.projects.initializr.BootDependenciesPanel.filter(BootDependenciesPanel.java:339)
	at com.github.alexfalappa.nbspringboot.projects.initializr.InitializrProjectPanelVisual2$FilterFieldListener.doFilter(InitializrProjectPanelVisual2.java:250)
	at com.github.alexfalappa.nbspringboot.projects.initializr.InitializrProjectPanelVisual2$FilterFieldListener.insertUpdate(InitializrProjectPanelVisual2.java:231)
	at java.desktop/javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:203)
...
```

**Comment by AlexFalappa** [comment]
This bug manifests when frequent dependencies from previous sessions make a group empty, i.e. if _Lombok_, _Configuration Processor_ and _Developer Tools_ have been used the _Developer Tools_ group is empty and disappear from an internal data structure.
