### ISSUE TITLE
Error when try to compile from source

### ISSUE THREAD

**Issue by blackleg** [AlexFalappa/nb-springboot#150]
I'm trying to build the plugin in Apache Netbeans 11.2.

```bash
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 /snap/netbeans/18/netbeans/java/maven/bin/mvn --errors -e -Pnetbeans-ide clean install
```
Maven throws this exception:

```--- nbm-maven-plugin:4.1:manifest (default-manifest) @ nb-springboot-plugin ---
NBM Plugin generates manifest
Adding on module's Class-Path:
    org.springframework.boot:spring-boot-configuration-metadata:jar:2.2.0.RELEASE
    com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1
    org.springframework:spring-web:jar:5.2.0.RELEASE
    org.springframework:spring-beans:jar:5.2.0.RELEASE
    org.springframework:spring-core:jar:5.2.0.RELEASE
    org.springframework:spring-jcl:jar:5.2.0.RELEASE
    org.springframework:spring-context:jar:5.2.0.RELEASE
    org.springframework:spring-aop:jar:5.2.0.RELEASE
    org.springframework:spring-expression:jar:5.2.0.RELEASE
    commons-lang:commons-lang:jar:2.6
    org.apache.commons:commons-collections4:jar:4.1
    com.fasterxml.jackson.core:jackson-databind:jar:2.10.0
    com.fasterxml.jackson.core:jackson-annotations:jar:2.10.0
    com.fasterxml.jackson.core:jackson-core:jar:2.10.0
    org.parboiled:parboiled-java:jar:1.1.8
    org.parboiled:parboiled-core:jar:1.1.8
    org.ow2.asm:asm:jar:5.2
    org.ow2.asm:asm-tree:jar:5.2
    org.ow2.asm:asm-analysis:jar:5.2
    org.ow2.asm:asm-util:jar:5.2
    com.github.drapostolos:type-parser:jar:0.6.0
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 7.046 s
Finished at: 2019-12-27T11:11:01+01:00
Final Memory: 37M/423M
------------------------------------------------------------------------
Failed to execute goal org.codehaus.mojo:nbm-maven-plugin:4.1:manifest (default-manifest) on project nb-springboot-plugin: Execution default-manifest of goal org.codehaus.mojo:nbm-maven-plugin:4.1:manifest failed. IllegalArgumentException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:nbm-maven-plugin:4.1:manifest (default-manifest) on project nb-springboot-plugin: Execution default-manifest of goal org.codehaus.mojo:nbm-maven-plugin:4.1:manifest failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-manifest of goal org.codehaus.mojo:nbm-maven-plugin:4.1:manifest failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.apache.maven.shared.dependency.analyzer.asm.DependencyClassFileVisitor.visitClass(DependencyClassFileVisitor.java:65)
	at org.apache.maven.shared.dependency.analyzer.ClassFileVisitorUtils.visitClass(ClassFileVisitorUtils.java:163)
	at org.apache.maven.shared.dependency.analyzer.ClassFileVisitorUtils.acceptJar(ClassFileVisitorUtils.java:107)
	at org.apache.maven.shared.dependency.analyzer.ClassFileVisitorUtils.accept(ClassFileVisitorUtils.java:61)
	at org.apache.maven.shared.dependency.analyzer.asm.ASMDependencyAnalyzer.analyze(ASMDependencyAnalyzer.java:50)
	at org.codehaus.mojo.nbm.NetBeansManifestUpdateMojo.buildDependencyClasses(NetBeansManifestUpdateMojo.java:920)
	at org.codehaus.mojo.nbm.NetBeansManifestUpdateMojo.buildProjectDependencyClasses(NetBeansManifestUpdateMojo.java:763)
	at org.codehaus.mojo.nbm.NetBeansManifestUpdateMojo.checkModuleClassPath(NetBeansManifestUpdateMojo.java:667)
	at org.codehaus.mojo.nbm.NetBeansManifestUpdateMojo.execute(NetBeansManifestUpdateMojo.java:530)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more```

**Comment by AlexFalappa** [comment]
@blackleg, I have seen this too.

Out of curiosity, which exact OpenJDK version are you using?

**Comment by AlexFalappa** [comment]
I am also trying to understand exactly when this happens, which NB/JDKs combinations trigger it.

**Comment by blackleg** [comment]
> @blackleg, I have seen this too.
> 
> Out of curiosity, which exact OpenJDK version are you using?

I use OpenJDK 8 version provided by [Ubuntu18.04 LTS package](https://packages.ubuntu.com/bionic/openjdk-8-jdk).
