### ISSUE TITLE
NullPointerException at com.github.alexfalappa.nbspringboot.projects.customizer.BootPanel.setModelHandle

### ISSUE THREAD

**Issue by ralphbenjamin** [AlexFalappa/nb-springboot#55]
https://netbeans.org/bugzilla/show_bug.cgi?id=268504

**Comment by AlexFalappa** [comment]
Which version of the NB Spring Boot plugin are you using?

**Comment by AlexFalappa** [comment]
Excerpt of stacktrace attached to NB bugzilla issue:
```
java.lang.NullPointerException
   at com.github.alexfalappa.nbspringboot.projects.customizer.BootPanel.setModelHandle(BootPanel.java:77)
   at com.github.alexfalappa.nbspringboot.projects.customizer.BootPanelProvider.createComponent(BootPanelProvider.java:48)
   at org.netbeans.spi.project.ui.support.ProjectCustomizer$DelegateCategoryProvider.create(ProjectCustomizer.java:629)
   at org.netbeans.modules.project.uiapi.CustomizerPane.setCategory(CustomizerPane.java:259)
   at org.netbeans.modules.project.uiapi.CustomizerPane.access$200(CustomizerPane.java:72)
   at org.netbeans.modules.project.uiapi.CustomizerPane$CategoryChangeListener.propertyChange(CustomizerPane.java:345)
```

**Comment by AlexFalappa** [comment]
Couldn't reproduce.
I added a null check at the line indicated in the stack trace.
