### ISSUE TITLE
annotation.IncompleteAnnotationException: org.springframework.web.bind.annotation.RequestMapping missing element path

### ISSUE THREAD

**Issue by ralphbenjamin** [AlexFalappa/nb-springboot#56]
https://netbeans.org/bugzilla/show_bug.cgi?id=268505

**Comment by AlexFalappa** [comment]
Which version of the NB Spring Boot plugin are you using?

**Comment by AlexFalappa** [comment]
Stacktrace from NB bugzilla issue:
```
java.lang.annotation.IncompleteAnnotationException: org.springframework.web.bind.annotation.RequestMapping missing element path
   at sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:81)
   at com.sun.proxy.$Proxy70.path(.java:0)
   at com.github.alexfalappa.nbspringboot.navigator.MappedElementExtractor.extractTypeLevelMappings(MappedElementExtractor.java:188)
   at com.github.alexfalappa.nbspringboot.navigator.MappedElementExtractor.visitClass(MappedElementExtractor.java:98)
   at com.github.alexfalappa.nbspringboot.navigator.MappedElementExtractor.visitClass(MappedElementExtractor.java:54)
   at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:798)
   at com.sun.source.util.TreeScanner.scan(TreeScanner.java:86)
   at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
   at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
   at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
   at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:579)
   at com.github.alexfalappa.nbspringboot.navigator.ElementScanningTaskFactory$ElementScanningTask$1.run(ElementScanningTaskFactory.java:73)
   at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
   at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
   at java.awt.EventQueue.access$500(EventQueue.java:97)
   at java.awt.EventQueue$3.run(EventQueue.java:709)
   at java.awt.EventQueue$3.run(EventQueue.java:703)
   at java.security.AccessController.doPrivileged(AccessController.java:0)
   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
   at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
   at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
   at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
   at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
   at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
   at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by AlexFalappa** [comment]
Couldn't reproduce.
I added a try/catch block that should fix the problem in master
