### ISSUE TITLE
Failed initializr project after upgrade NB 8.2

### ISSUE THREAD

**Issue by finzaiko** [AlexFalappa/nb-springboot#58]
After I upgrade my netbeans to 8.2 I got an error stack on "Contacting service"
Caused: org.springframework.web.client.HttpClientErrorException: 403 Forbidden; nested exception is 
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:667)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:620)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:595)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:557)
	at com.github.alexfalappa.nbspringboot.projects.initializr.InitializrService.getMetadata(InitializrService.java:68)
	at com.github.alexfalappa.nbspringboot.projects.initializr.InitializrProjectWizardPanel1.getInitializrMetadata(InitializrProjectWizardPanel1.java:122)
[catch] at com.github.alexfalappa.nbspringboot.projects.initializr.InitializrProjectPanelVisual1.construct(InitializrProjectPanelVisual1.java:332)
	at org.openide.util.AsyncInitSupport.run(AsyncInitSupport.java:168)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

**Comment by AlexFalappa** [comment]
I cannot reproduce it on my side. It looks like a temporary network problem.

Are you behind a corporate firewall / proxy? That may be the cause.

**Comment by finzaiko** [comment]
I turn off the firewall and turn on again work fine now.
Nothing change before I upgrade(firewall/proxy)
http://statistics.netbeans.org/analytics/exception.do?id=837505
Thanks.
