### ISSUE TITLE
NullPointer when try add new Configuration Properties

### ISSUE THREAD

**Issue by rafaeldev** [AlexFalappa/nb-springboot#78]
Hi Master Alex!

Below are the netbeans log:

```
java.lang.NullPointerException
	at com.github.alexfalappa.nbspringboot.projects.service.spi.SpringBootServiceImpl.updateCacheMaps(SpringBootServiceImpl.java:234)
	at com.github.alexfalappa.nbspringboot.projects.service.spi.SpringBootServiceImpl.queryPropertyMetadata(SpringBootServiceImpl.java:196)
	at com.github.alexfalappa.nbspringboot.projects.customizer.CfgPropsDialog.loadCfgProps(CfgPropsDialog.java:91)
	at com.github.alexfalappa.nbspringboot.projects.customizer.BootPanel.bAddActionPerformed(BootPanel.java:390)
	at com.github.alexfalappa.nbspringboot.projects.customizer.BootPanel.access$600(BootPanel.java:50)
	at com.github.alexfalappa.nbspringboot.projects.customizer.BootPanel$8.actionPerformed(BootPanel.java:276)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at org.netbeans.core.windows.services.NbPresenter.superShow(NbPresenter.java:1086)
	at org.netbeans.core.windows.services.NbPresenter.doShow(NbPresenter.java:1136)
	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:1108)
	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:131)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEventAccess(NbMutexEventProvider.java:138)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.readAccess(NbMutexEventProvider.java:98)
	at org.netbeans.modules.openide.util.LazyMutexImplementation.readAccess(LazyMutexImplementation.java:94)
	at org.openide.util.Mutex.readAccess(Mutex.java:218)
	at org.netbeans.core.windows.services.NbPresenter.show(NbPresenter.java:1093)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at org.netbeans.modules.maven.customizer.CustomizerProviderImpl$1.run(CustomizerProviderImpl.java:188)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEvent(NbMutexEventProvider.java:118)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.readAccess(NbMutexEventProvider.java:93)
	at org.netbeans.modules.openide.util.LazyMutexImplementation.readAccess(LazyMutexImplementation.java:89)
	at org.openide.util.Mutex.readAccess(Mutex.java:260)
	at org.netbeans.modules.maven.customizer.CustomizerProviderImpl.showCustomizer(CustomizerProviderImpl.java:170)
	at org.netbeans.modules.maven.customizer.CustomizerProviderImpl.showCustomizer(CustomizerProviderImpl.java:138)
	at org.netbeans.modules.maven.customizer.CustomizerProviderImpl.showCustomizer(CustomizerProviderImpl.java:133)
	at org.netbeans.modules.project.ui.actions.CustomizeProject$1$1.run(CustomizeProject.java:160)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```
I am using: 
OS: Win 7 Ultimate
IDE: NetBeans IDE 8.2 (Build 201609300101)
NB Spring Boot 1.5 Version

**Comment by AlexFalappa** [comment]
@rafaeldev will try to reproduce it. 
From the stacktrace it seems you clicked on the add configuration property override button in the project properties dialogue right?

**Comment by rafaeldev** [comment]
@AlexFalappa right, I did it!
It's happening in my Netbeans in my company.
Today in my house I had this same error, but when I tried reproduce again this error I don't had the same results...

The sequence was:

1. Update the NB Spring Boot;
2. Create New App with "Spring Boot Initializr Project";
3. add Eureka Discover dependecy;
4. Resolve the conflicts with "clean and build" operation;
5. Open Properties of project;
6. Click in "Spring Boot" Category;
7. and click em plus button at "Override Configuration Properties";

After these steps a had the error, but when I deleted de app project on netbeans and repeat these steps the error doesn't reproduced...

**Comment by AlexFalappa** [comment]
I managed in reproducing the issue, which as you reported does not always happen, and I am fixing it in master.

As a workaround you can close and reopen the project after step 3, it should fix it.

By the way, in v1.5 step 4 should no longer be needed as a maven dependency download is triggered after generating the project, leave it some time and you should notice NetBeans is performing some background job.
