### ISSUE TITLE
NPE when opening a spring-boot project

### ISSUE THREAD

**Issue by sworisbreathing** [AlexFalappa/nb-springboot#80]
I'm on NetBeans 8.2 with nb-springboot 1.5.
When I try to open a particular Maven/Spring-Boot project, I get a NullPointerException in the IDE and the project will not load (does not appear in the Projects window). The stack trace from the IDE log is:
```
java.lang.NullPointerException
	at com.github.alexfalappa.nbspringboot.projects.service.spi.SpringBootServiceImpl.init(SpringBootServiceImpl.java:137)
	at com.github.alexfalappa.nbspringboot.projects.service.spi.SpringBootServiceInitializer.projectOpened(SpringBootServiceInitializer.java:56)
	at org.netbeans.spi.project.ui.ProjectOpenedHook$1.projectOpened(ProjectOpenedHook.java:85)
[catch] at org.netbeans.modules.project.ui.OpenProjectList.notifyOpened(OpenProjectList.java:1298)
	at org.netbeans.modules.project.ui.OpenProjectList.doOpenProject(OpenProjectList.java:1379)
	at org.netbeans.modules.project.ui.OpenProjectList.open(OpenProjectList.java:823)
	at org.netbeans.modules.project.ui.OpenProjectList$6.run(OpenProjectList.java:675)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
```

Looking at the code, it appears that `cpExec` hasn't been initialized in this particular case for this project, which I assume means it hasn't found a source group with the word `source` in it. I'm going to have a look through the maven project to see if I can understand why this happens for this particular project, but there should probably be some sort of warning logged in this scenario

**Comment by sworisbreathing** [comment]
I think I've got a fix for this. Will open a PR once I've successfully tested it locally.
